#!/bin/sh

if [ ! -d "~/.aws" ]
then
    mkdir ~/.aws
fi

if [ $# -eq 0 ]
then
    docker run -it -v ~/.aws:/root/.aws cgswong/aws:latest aws --version
else
    docker run -it -v ~/.aws:/root/.aws cgswong/aws:latest aws $1
fi
